services:
  frontend:
    image: sscwebapphw/frontend
    build:
      context: ../..
    container_name: frontend
    environment:
      - VIRTUAL_HOST=muictalk.64-ssc.com
      - LETSENCRYPT_HOST=muictalk.64-ssc.com
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=/
      - VUE_API_URL=https://muictalk.64-ssc.com
    ports:
      - "8080:80"
    networks:
      - webapp
networks:
  webapp:
    external: true